### ISSUE TITLE
meteor add error

### ISSUE THREAD

**Issue by nicejwjin** [acidsound/meteor-accounts-kakao#1]
meteor add spectrum:accounts-kakao

 => Errors while adding packages:             

While selecting package versions:
error: unknown package: isobuild:isopack-2
Required by: spectrum:kakao 0.0.1

same for meteor add spectrum:kakao eitehr

kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk

**Comment by nicejwjin** [comment]
meteor version METEOR@1.1.0.2

**Comment by acidsound** [comment]
그렇다고 하네요. 제가 Meteor를 development 버전을 쓰고 있어서 isopack-2를 쓰는 걸로 보이는데

stable 버전인 컴에서 다시 올려야겠어요.

**Comment by acidsound** [comment]
https://github.com/acidsound/meteor-kakao 를 stable버전에서 다시 publish 했습니다. 소스 수정은 없고 version만 0.0.2로 갱신했어요.
